bases:
  - ../anton-split
patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ing
    path: ingress-patch.yaml
  - target:
      version: v1
      kind: Service
      name: svc
    path: service-patch.yaml