bases:
  - ../base
namespace: anton
commonLabels:
  dep: anton
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dep
    path: replica-count.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dep
    path: deployment-patch.yaml
  - target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: hpa
    path: hpa-patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ing
    path: ingress-patch.yaml
patchesStrategicMerge:
  - |-
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: svcm
    $patch: delete