{
 "title": "ZeroK Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace1",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "namespace2",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   { "name": "num_panels" }
  ]
 },
 "panels": [
  { "title": "Scripts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "\n<br>\n<a \nhref=\"http://load-test.zerok.ai/start\"  \ntarget=\"_blank\"\nstyle=\"\n  border-radius: 7px; \n  margin: 0.25rem; \n  border: 1px solid;\n  text-decoration: none; \n  padding: 1rem 1.5rem; \n  width: 100px;\n  line-height: 10px;\n  font-size: 36px;\n  text-align: center;\"\ntitle=\"Run test\">\n▶️</a>\n\n<a \nhref=\"http://load-test.zerok.ai/status\"  \ntarget=\"_blank\"\nstyle=\"\nborder-radius: 7px; \nmargin: 0.25rem 0.30rem; \nborder: 1px solid;\ntext-decoration: none; \npadding: 1rem 1.5rem; \nwidth: 100px;\nline-height: 100px;\nfont-size: 36px;\ntext-align: center\"\ntitle=\"Logs\">\n🪵</a>\n<a \nhref=\"http://load-test.zerok.ai/reset\"\ntarget=\"_blank\"\nstyle=\"\nborder-radius: 7px; \nmargin: 0.25rem 0.30rem; \nborder: 1px solid;\ntext-decoration: none; \npadding: 1rem 1.5rem; \nwidth: 100px;\nline-height: 100px;\nfont-size: 36px;\ntext-align: center\"\ntitle=\"Reset the state\">\n🔂</a>\n<!--\n<a \nhref=\"https://aax7mshw45.execute-api.us-east-2.amazonaws.com/default/shutdown\"  \ntarget=\"_blank\"\nstyle=\"\nborder-radius: 7px; \nmargin: 0.25rem 0.30rem; \nborder: 1px solid;\ntext-decoration: none; \npadding: 1rem 1.5rem; \nwidth: 100px;\nline-height: 100px;\nfont-size: 36px;\ntext-align: center\"\ntitle=\"Kill demo machines\">\n🔥</a>\n-->"
   }
  },
  {
   "title": "Tuning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Sets - $namespace1",
     "type": "text",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
     "options": {
      "content": "\n| Pod         | Count | CPU (m) | Memory (MI) | Req. per pod |\n|-------------|-------|---------|-------------|--------------|\n| All         | `4`   | `170`   | `200`       | `1500`/min   |\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Resource Sets - $namespace2",
     "type": "text",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
     "options": {
      "content": "| Pod         | Count | CPU (m) | Memory (MI) | Req. per pod |\n|-------------|-------|---------|-------------|--------------|\n| High Memory | `2`   | `175`   | `220`       | `1500`/min   |\n| Others      | `2`   | `165`   | `180`       | `1500`/min   |\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "HighMem",
     "type": "text",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
     "options": {
      "content": "\n![HighMem](https://zerok.ai/assets/HighMem.png)\n"
     }
    },
    {
     "title": "Others",
     "type": "text",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
     "options": {
      "content": "\n![HighCpu](https://zerok.ai/assets/HighCPU.png)\n"
     }
    }
   ]
  },
  { "title": "Test run", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Request count - base",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(scenario, error_code) (k6_http_reqs{scenario=~\"base_.*\"})",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Request count - $namespace2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by(scenario, error_code) (k6_http_reqs{scenario=~\"anton_.*\"})",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Impact - CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilisation (from requests) - $namespace1",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace1\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "CPU Utilisation (from requests) - $namespace1",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace1\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "CPU Utilisation (from requests) - $namespace2",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace2\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "CPU Utilisation (from limits) - $namespace2",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace2\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "CPU Usage per Pod - $namespace1",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace1\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$namespace1\"}) by (pod)) * 100  ",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "CPU Usage per Pod - $namespace2 - highmem",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace2\", pod=~\"dep-zerok-rest.*\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$namespace2\", pod=~\"dep-zerok-rest.*\"}) by (pod)) * 100  ",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "CPU Usage per Pod - $namespace2 - others",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace2\", pod=~\"dep-zerok-highcpu.*\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$namespace2\", pod=~\"dep-zerok-highcpu.*\"}) by (pod)) * 100  ",
       "legendFormat": "  "
      }
     ]
    }
   ]
  },
  {
   "title": "Impact - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilisation (from requests) - $namespace1",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace1\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Memory Utilisation (from limits) - $namespace1",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace1\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Memory Utilisation (from requests) - $namespace2",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace2\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Memory Utilisation (from limits) - $namespace2",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace2\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Memory Usage per Pod - $namespace1",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace1\", container!=\"\", image!=\"\"} / 1000000) by (pod)",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Memory Usage per Pod - $namespace2 - highCPU",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace2\", container!=\"\", image!=\"\", pod=~\"dep-zerok-highcpu.*\"} / 1000000) by (pod)",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Memory Usage per Pod - $namespace2 - Others",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace2\", container!=\"\", image!=\"\", pod=~\"dep-zerok-rest.*\"} / 1000000) by (pod)",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Latency - $namespace1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "k6_custom_base_highcpu_duration_avg{}",
     "legendFormat": "{{tag}}"
    },
    {
     "expr": "k6_custom_base_highmem_duration_avg{}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Latency - $namespace2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "k6_custom_anton_highcpu_duration_avg{}",
     "legendFormat": "{{tag}}"
    },
    {
     "expr": "k6_custom_anton_highmem_duration_avg{}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "CPU Usage : $namespace1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"cpu\"}) * 1000\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace1\"}) by (namespace) * 1000",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"cpu\"}) * 1000\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "CPU Usage : $namespace2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"cpu\"}) * 1000\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace2\"}) by (namespace) * 1000",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"cpu\"}) * 1000\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "Memory Utilization - $namespace1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace1\", container!=\"POD\", image!=\"\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"memory\"}\n)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace1\", resource=\"memory\"}\n)\n",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Utilization - $namespace2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace2\", container!=\"POD\", image!=\"\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"memory\"}\n)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"memory\"}\n)\n",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}