controller:
  ingressClassResource:
    name: anton-nginx  # default: nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/anton-ingress-nginx"  # default: k8s.io/ingress-nginx
  replicaCount: 4
  nodeSelector: {
    role: system,
    beta.kubernetes.io/os: linux
  }
  metrics:
    enabled: true
    serviceMonitor: 
      enabled: true
      additionalLabels: {
        release: "prometheus"
        
      }
  # Limit the scope of the controller to a specific namespace
  scope:
    # -- Enable 'scope' or not
    enabled: true
    # -- Namespace to limit the controller to; defaults to $(POD_NAMESPACE)
    namespace: anton
defaultBackend:
  nodeSelector: {
    role: system,
    beta.kubernetes.io/os: linux
  }
  