controller:
  ingressClassResource:
    name: anton-nginx  # default: nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/anton-ingress-nginx"  # default: k8s.io/ingress-nginx
  replicaCount: 4
  nodeSelector: {
    role: system,
    beta.kubernetes.io/os: linux
  }
  metrics:
    enabled: true
    serviceMonitor: 
      enabled: true
      additionalLabels: {
        release: "prometheus"
        
      }
defaultBackend:
  nodeSelector: {
    role: system,
    beta.kubernetes.io/os: linux
  }
  