controller:
  replicaCount: 4
  nodeSelector: {
    role: system,
    beta.kubernetes.io/os: linux
  }
  metrics:
    enabled: true
    serviceMonitor: 
      enabled: true
      additionalLabels: {
        release: "prometheus"
      }
  # Limit the scope of the controller to a specific namespace
  scope:
    # -- Enable 'scope' or not
    enabled: true
    # -- Namespace to limit the controller to; defaults to $(POD_NAMESPACE)
    namespace: base

defaultBackend:
  nodeSelector: {
    role: system,
    beta.kubernetes.io/os: linux
  }
  