apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-deployment
  namespace: load-test
  labels:
    app: myapp
    dep: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      dep: default
  template:
    metadata:
      labels:
        app: myapp
        dep: default
    spec:
      nodeSelector: {
        role: worker
      }
      containers:
      - name: load-test
        image: 301129966109.dkr.ecr.us-east-2.amazonaws.com/nodeexample
        imagePullPolicy: Always
        ports:
        - name: m-http
          containerPort: 3000
        resources: 
          requests: 
            cpu: 150m
            memory: 170Mi
          limits:
            cpu: 170m
            memory: 200Mi 
