apiVersion: v1
kind: Service
metadata:
  name: load-test-service
  namespace: app
  labels:
    app: load-test
    load: any
spec:
  selector:
    app: load-test
    load: any
  type: ClusterIP # LoadBalancer # NodePort # 
  ports:
    - protocol: TCP
      name: m-http  
      port: 80
      targetPort: 3000