apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: load-test-service-monitor
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  endpoints:
  - port: m-http
    path: /metrics
  namespaceSelector:
    any: true