apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: load-test-autoscaler
  namespace: app
  labels:
    load: low
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-test
  minReplicas: 1
  maxReplicas: 60
  targetCPUUtilizationPercentage: 60
