apiVersion: v1
kind: Namespace
metadata:
  name: app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  namespace: app
  labels:
    app: load-test
spec:
  selector:
    matchLabels:
      app: load-test
  template:
    metadata:
      labels:
        app: load-test
        app.kubernetes.io/name: prometheus
        load: "any"
    spec:
      containers:
      - name: load-test
        image: 301129966109.dkr.ecr.us-east-2.amazonaws.com/nodeexample
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources: 
          requests: 
            cpu: 50m
          limits: 
            cpu: 100m

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: load-test-autoscaler-kube
  namespace: app
  labels:
    app.kubernetes.io/name: prometheus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-test
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 30
