- op: replace
  path: /metadata/name
  value: ing-anton
- op: replace
  path: /spec/rules/0/host
  value: with.getanton.com
- op: replace
  path: /metadata/annotations/kubernetes.io~1ingress.class
  value: anton-nginx