bases:
  - ../default-setup
namespace: anton
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dep
    path: replica-count.yaml
patchesStrategicMerge:
  - |-
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: svcm
    $patch: delete